### ISSUE TITLE
Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by langrenbule** [alibaba/dexposed#71]
[INFO] *********************_系统崩溃信息**_*******************:
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    at dalvik.system.DexFile.defineClassNative(Native Method)
    at dalvik.system.DexFile.defineClass(DexFile.java:222)
    at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:215)
    at dalvik.system.DexPathList.findClass(DexPathList.java:322)
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
我在使用过程中,与遇到以上的问题，根据度娘的提示，补丁与宿主APK的jar包冲突了？

**Comment by langrenbule** [comment]
## OK，I Know

provided files('libs/dexposedbridge.jar')
provided files('libs/patchloader.jar')

# provided not compile
