### ISSUE TITLE
红米Note2 MIUI8 5.0.1闪退，dev_art

### ISSUE THREAD

**Issue by dovewi** [alibaba/dexposed#79]
闪退 MIUI8 红米note2
```03-07 22:18:45.004 24782-24782/io.virtualapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: io.virtualapp, PID: 24782
                                                               java.lang.RuntimeException: Unable to create application io.virtualapp.VApp: java.nio.BufferUnderflowException
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4775)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                Caused by: java.nio.BufferUnderflowException
                                                                   at java.nio.ByteArrayBuffer.getLong(ByteArrayBuffer.java:211)
                                                                   at com.taobao.android.dexposed.utility.Platform$Platform64Bit.orderByteToLong(Platform.java:103)
                                                                   at com.taobao.android.dexposed.art.method.Field.readLong(Field.java:75)
                                                                   at com.taobao.android.dexposed.art.method.ArtMethodV19.getEntryPointFromQuickCompiledCode(ArtMethodV19.java:68)
                                                                   at com.taobao.android.dexposed.art.hook.Operator.<init>(Operator.java:38)
                                                                   at com.taobao.android.dexposed.art.hook.OperatorU.<init>(OperatorU.java:24)
                                                                   at com.taobao.android.dexposed.art.hook.Scenario.hookMethod(Scenario.java:76)
                                                                   at com.taobao.android.dexposed.art.hook.Scenario.hookMethod(Scenario.java:105)
                                                                   at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:118)
                                                                   at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:153)
                                                                   at io.virtualapp.VApp.onCreate(VApp.java:50)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) ```

**Comment by hwjump** [comment]
thank you for response. I will see it.
